title: Corina Acosta
description: "Boston-based Web Developer, Teacher, Dancer turned Ashtangi, photograhper, dog lover, health food nut, and passionate about creating apps to promote social change."
keywords: "Web Developer, Boston, Teacher, Ashtangi, Dancer, Photographer, App Developer"
author: Corina Acosta
markdown: redcarpet
#extensions: [fenced_code_blocks]
port: 4000
pygments: true
permalink: /:categories/:year/:month/:day/:title 
exclude: ["README.md", "sass", ".sass-cache"]
production_url : http://www.iamcorinaacosta.com
rss_path: /rss.xml
paginate: 5
paginate_path: "/page:num"
excerpt_separator: "\n\n"
prose:
  rooturl: '_posts'
  siteurl: 'http://www.iamcorinaacosta.com'
  media: 'media'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          alterable: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          alterable: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Category"
          options: "http://www.iamcorinaacosta.com/categories.jsonp"
          alterable: true
      - name: "author"
        field:
          element: "hidden"
          value: "Corina Acosta"
      - name: "comments"
        field:
          element: hidden
          label: "Comments"
          value: "true"
      - name: "tags"
        field:
          element: "hidden"
          label: "Tags"
          placeholder: "Choose Tags"
          alterable: true
    _drafts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          alterable: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          alterable: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Category"
          options: "http://www.iamcorinaacosta.com/categories.jsonp"
          alterable: true
      - name: "author"
        field:
          element: "hidden"
          value: "Corina Acosta"
      - name: "comments"
        field:
          element: hidden
          label: "Comments"
          value: "true"
      - name: "tags"
        field:
          element: "hidden"
          label: "Tags"
          placeholder: "Choose Tags"
          alterable: true